# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bz-o297_W-kLmgzXtIj4JQBftsP1AhP4
"""

import pandas as pd
import numpy as np

data={'name':['jeetu','aditya','anshuman','gaurav'],'age':['18','17','20','19'],'city':['barielly','himachal','bihar','uttarakhand']}
df=pd.DataFrame(data)
print(df)

ages=np.array(df['age'])
print(ages)

m=pd.Series(ages)
print(m)

a=pd.Series(['java','c','c++',np.nan])
a.map({'java':'core'})

a.map('i like{}'.format,na_action='ignore')